services:
  postgres-main:
    image: 'postgres:latest'
    container_name: postgres-main
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  rabbit-main:
    image: 'rabbitmq:management'
    container_name: rabbitmq-main
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
  redis:
    image: 'redis:latest'
    container_name: redis-main
    ports:
      - "6379:6379"