spring:
    data:
        mongodb:
            host: localhost
            port: 27017
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 110MB
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        password: root
        username: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
    main:
        multipart:
            max-file-size: 1000MB
            max-request-size: 100MB
    rabbitmq:
        host: localhost
        username: admin
        password: admin
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: 0e10299ccb71a3fb435f
                        clientSecret: c11073070842ae33e89eaf07894cd73a6828cd4e
                        redirect-uri: http://localhost:4200/login/oauth2/code/github
                        token-uri: https://github.com/login/oauth/access_token
angular:
    client:
        url: http://localhost:4200
security:
    secretKey: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
elastic:
    username: "changeme"
    password: "changeme"
files:
    media: "/home/pag/Dokumenty/GooGee-media/"
